---

- name: Check where bash is installed
  command: which bash
  register: packer_check_bash_path
  failed_when: false
  changed_when: false

- name: Check that unzip is installed
  command: which unzip
  register: packer_check_unzip_installed
  failed_when: false
  changed_when: false

- name: Fail play if unzip is not installed
  fail:
    msg: unzip was not found and is required for unpacking packer, please ensure this is installed.
  when: packer_check_unzip_installed.rc > 0
        and not packer_install_os_dependencies

- name: Check for existing packer binary
  stat:
    path: "{{ packer_install_dir }}/packer"
  register: packer_check_existing

- name: Check packer binary version if binary already exists
  shell: |
    set -o pipefail
    {{ packer_install_dir }}/packer version | awk '{ print $NF }' | sed 's/^v//'
  args:
    executable: "{{ packer_check_bash_path.stdout_lines[0] }}"
  changed_when: false
  register: packer_check_existing_version
  when: packer_check_existing.stat.exists